spring.application.name=AI Chatbot Asset
server.port=8082

spring.data.mongodb.uri=mongodb+srv://akhilteja123_db_user:PCJfCNX93A9C27m6@cluster0.7tgyqlw.mongodb.net/chatdb?retryWrites=true&w=majority

#langchain4j.open-ai.chat-model.api-key=${OPENAI_API_KEY}
#langchain4j.open-ai.chat-model.model-name=gpt-4o-mini
#langchain4j.open-ai.chat-model.log-requests=true
#langchain4j.open-ai.chat-model.log-responses=true

#langchain4j.open-ai.streaming-chat-model.api-key=${OPENAI_API_KEY}
#langchain4j.open-ai.streaming-chat-model.model-name=gpt-4o-mini
#langchain4j.open-ai.streaming-chat-model.log-requests=true
#langchain4j.open-ai.streaming-chat-model.log-responses=true

logging.level.dev.langchain4j=DEBUG

management.endpoints.web.exposure.include=*
management.tracing.sampling.probability=1

management.tracing.enabled=false
management.zipkin.tracing.enabled=false

#ollama ----
#langchain4j.ollama.chat-model.base-url=http://localhost:11434
#langchain4j.ollama.chat-model.model-name=llama3
#langchain4j.ollama.chat-model.temperature=0.7
#langchain4j.ollama.chat-model.timeout=60s
#langchain4j.ollama.chat-model.max-tokens=512



#Groq -----
langchain4j.open-ai.chat-model.base-url=https://api.groq.com/openai/v1
langchain4j.open-ai.chat-model.api-key=${OPENAI_API_KEY}
langchain4j.open-ai.chat-model.model-name=llama-3.3-70b-versatile
langchain4j.open-ai.chat-model.temperature=0.7
langchain4j.open-ai.chat-model.timeout=60s

